### ISSUE TITLE
Implement a prototype for the generalized-alpha solver

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#22]
We would like to implement a prototype version of the generalized-alpha time integration scheme into OpenTurbine as part of the proof-of-concept (POC) study to model the dynamics of a rigid pendulum. To achieve this, we want to implement the algorithm presented in the [paper by Arnold and Bruls](https://link.springer.com/article/10.1007/s11044-007-9084-0). A basic description of the generalized-alpha method and the algorithm for constrained, nonlinear structural dynamics problems is provided in the [Overleaf document for the POC](https://www.overleaf.com/read/jrxxvrckpspb) (Section 5.1).

**Comment by jjonkman** [comment]
@faisal-bhuiyan -- Overall, the generalized alpha scheme looks fine.  Can I suggest, though, that we you implement the Newton iterations in terms of incremental accelerations rather than incremental displacements?  I find this a more natural choice for structural dynamics problems and the Jacobians needed; this is also what we are using in the tight coupling algorithm being implemented now in OpenFAST.

In general, supporting algebraic constraints as proposed proposed looks fine.  But I would encourage the use of relative coordinates and algebraic elimination of constraints in the multi-body formulation of OpenTurbine as much as possible. The solution will be much more computationally efficient with fewer algebraic constraints.

**Comment by michaelasprague** [comment]
@jjonkman Thanks for the comments and suggestion, and we will keep them under consideration.  At least for this proof-of-concept problem, we are interested in testing the displacement-based DAE-3 formulation, which is appealing for its simplicity.
