### ISSUE TITLE
Add regression test for heavy top problem

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#45]
The heavy top problem is a classic benchmark in mechanics that involves the motion of a rigid body subjected to gravity. We should look into creating a regression test for OpenTurbine based on the heavy top problem described in [Brüls and Cardona](https://asmedigitalcollection.asme.org/computationalnonlinear/article-abstract/5/3/031002/384896/On-the-Use-of-Lie-Group-Time-Integrators-in?redirectedFrom=fulltext).

**Comment by rafmudaf** [comment]
Here are a few thoughts to get this going:

- Google Test can handle regression tests directly, so there's no need to use a separate framework.
- Organizationally, regression tests are typically separated from unit tests primarily for the sake of dealing with the baseline results. While OpenTurbine doesn't yet have large outputs or output files, it might be good to establish a file structure that would support storing (and updating) a large set of baselines.
- Since regression tests are system-level tests, they tend to take longer to run than unit tests. It may be good to create a reg test driver that is run less frequently than unit tests during development. For example, as I'm working on a feature, I may run the unit tests on an ongoing basis. However, I typically let GitHub Actions run the regression tests after I push to GitHub.

The structure of the tests themselves will be dependent on the structure of the outputs and output files. Since that's not in place yet, a good first step to establishing a regression test system is:
- [ ] Create the reg test executable
- [ ] Organize the test files in such a way that supports quickly updating baselines
- [ ] Convert any of the unit tests that function more like a regression test

**Comment by deslaughter** [comment]
Reformulate in terms of global rotations
